### ISSUE TITLE
哔哩哔哩客户端：读取列表异常

### ISSUE THREAD

**Issue by mavnp** [10miaomiao/bili-down-out#2]
手机型号：HarmonyOS 2.0
已授予所有已需权限，有一段时间可以正常使用(bilimiao一直都能用，哔哩哔哩客户端出现此问题)

如图所示

![Screenshot_20240506_230226_cn.a10miaomiao.bilidown.jpg](https://github.com/10miaomiao/bili-down-out/assets/92003405/e35995bd-70de-4259-82c6-f61250d8fafb)

**Comment by mrliu646** [comment]
如果下载的视频属于合集，就会出现此问题
因为合集视频的 entry.json 文件没有 "part" 和 "vid" 这两个对象
例子: av213939454
