### ISSUE TITLE
[Feature Request] 支持添加任务到等待队列

### ISSUE THREAD

**Issue by prinsss** [10miaomiao/bili-down-out#3]
## 需求描述

首先感谢作者开发的 App，配合 Shizuku 成功导出了客户端的缓存视频，非常好用！谢谢🙏

不过我在使用过程中发现了一些或许可以优化的地方，所以过来反馈一下～

1. 在创建导出任务时，希望可以支持添加到等待队列
2. 填写导出文件名时，希望可以支持带空格的文件名
3. 在浏览缓存的视频时，希望可以通过关键字搜索

## 当前结果

1. 如果当前已经有导出任务在运行，尝试创建新任务会提示「有视频正在导出中，请稍后再试」
2. 如果输入的文件名中包含空格，会提示「文件名不能含有格」
3. 可以正常浏览已缓存的视频，但不支持搜索

## 期望结果

1. 希望可以添加多个任务到等待队列，等当前导出任务执行完毕后，自动执行下一个任务（当想要一次导出很多视频时会比较方便，现在只能慢慢等一个视频导出完成后，再手动导出下一个）
2. 希望可以使用带空格的文件名（不少 UP 主上传的标题就是带空格的，现在只能每次手动把空格去掉）
3. 希望可以通过关键词搜索已缓存的视频（我缓存了几百个视频，找的时候有点大海捞针了😂）

只是一些小的建议，核心导出功能都是 OK 的，再次感谢～

## 使用环境

系统版本: Android 14
App 版本: 0.4 beta

**Comment by 10miaomiao** [comment]
1.0版本已支持任务队列，搜索功能和批量操作功能等待后续更新
