### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [10miaomiao/bili-down-out#5]
请问可以将这个应用发布到 F-Droid 吗？

**Comment by 10miaomiao** [comment]
已发布1.0版本，可以的话帮我发布到F-Droid，(´▽`ʃ♡ƪ)

**Comment by linsui** [comment]
每个 abi 需要不同的 version code，麻烦参照 https://github.com/nfcim/nfsee/blob/master/android/app/build.gradle#L99 设置一下，可以设置成 1001, 1002, 1003, 1004。

**Comment by 10miaomiao** [comment]
> 每个 abi 需要不同的 version code，麻烦参照 https://github.com/nfcim/nfsee/blob/master/android/app/build.gradle#L99 设置一下，可以设置成 1001, 1002, 1003, 1004。

好的，已重新发布1.0版本

**Comment by linsui** [comment]
https://github.com/10miaomiao/bili-down-out/blob/master/app/build.gradle#L88 按照这里的设置 x86 的 version code 是 1001，release 里的 apk version code 是对的，但 BuildConfig 里的 version code 却是 1003。可能是没有清缓存？

**Comment by 10miaomiao** [comment]
这是正常的：https://issuetracker.google.com/issues/37008496

> https://github.com/10miaomiao/bili-down-out/blob/master/app/build.gradle#L88 按照这里的设置 x86 的 version code 是 1001，release 里的 apk version code 是对的，但 BuildConfig 里的 version code 却是 1003。可能是没有清缓存？

这是正常的：https://issuetracker.google.com/issues/37008496

**Comment by 10miaomiao** [comment]
> https://github.com/10miaomiao/bili-down-out/blob/master/app/build.gradle#L88 按照这里的设置 x86 的 version code 是 1001，release 里的 apk version code 是对的，但 BuildConfig 里的 version code 却是 1003。可能是没有清缓存？

这是正常的：https://issuetracker.google.com/issues/37008496

**Comment by linsui** [comment]
好，我知道问题在哪里了

**Comment by linsui** [comment]
为什么应用需要网络权限？

**Comment by 10miaomiao** [comment]
> 为什么应用需要网络权限？

显示视频封面

**Comment by linsui** [comment]
麻烦去掉 DependencyInfoBlock，这个块是用 Google 的公钥加密的，只有 Google 能读取。https://developer.android.com/studio/build/dependencies#dependency-info-play

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

需要更新一下 apk

**Comment by linsui** [comment]
https://github.com/10miaomiao/bili-down-out/blob/master/fastlane/metadata/android/zh-CN/changelogs/1000.txt 这个文件名要对应最高版本号也就是 1004 或者用 default.txt 也可以

**Comment by 10miaomiao** [comment]
已重命名

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16131 大概一周内能发布，感谢 :+1:

**Comment by 10miaomiao** [comment]
Okay, tq
